### ISSUE TITLE
Markera delar som ska mörkläggas

### ISSUE THREAD

**Issue by Herkarl** [datasektionen/styrdokument-bawang#1]
Just nu ganska jobbigt för folk när styrdokumenten inte är tillgängliga under sommaren, går att lösa genom att ge folk tillgång till github, men är lite meh.

Skulle nog tyvärr kräva en del arbete.

**Comment by foodelevator** [comment]
Det är bara reglementet och antagligen stadgarna som det finns någon mening med att mörklägga. Det känns som att det bästa vore att lägga till inloggning på sidan och att man kan välja vilka sidor som endast ska visas om man är inloggad, sektionsmedlem, och inte nØllan.

Detta borde göras innan nästa mottagning.

**Comment by Herkarl** [comment]
Två potentiella lösningar som jag tänkt på:
- _Lätt men grovkornig lösning_: lägga till tagg i `meta.toml`-filerna som markerar ett styrdokument som känsligt, och låta `taitan` antingen gömma filerna helt eller returnera nån 404-sida i html-fältet istället med eventuella instruktioner för hur man kommer åt dokumentet
- _Finkornig lösning som är lite oklar hur man bäst implementerar_: ha något sätt att i markdown:en markera känsliga avsnitt, och sedan censurera dem på antingen `taitan`- eller `bawang`-nivå
  - Typ slänga nån html-tagg runt texten med något speciellt attribut?
  - Gör man det på `bawang`-nivå så kommer användaren kunna hitta det som är gömt genom att kolla på requetsen, för content på sidor kan vara client-side rendrerat (iaf på datasektionen.se, kanske lite annorlunda på styrdokument).
  - Gör man det på `taitan`-nivå så garanterar man att slutanvändaren inte får datan, men det kommer nog göra det mycket mer komplext att implementera, eftersom vi måste lägga till att `taitan` går in och faktiskt kollar på html-contenten den genererar (det gör just nu med ett bibliotek).
 
Gör man det här så vill man nog göra det tydligt att något har censurerats, vet inte hur "juridiskt" bra det är att gömma delar av styrdokumenten utan något tecken på det. Man kan nog göra det på ett tema-enligt sätt så det är mottagningsvänligt.

Är nog typ lika komplext att inloggningsanpassa på båda dessa iom att ingen av `bawang`erna eller `taitan` har autentiseringsstöd för tillfället.
Båda lösningar skulle nog gå att återanvända till viss del för `datsektionen.se`, men ju större andel logik man lägger i `taitan` desto simplare blir det.

Lösningarna ska ju självklart interagera med [Darkmode](https://github.com/datasektionen/centralt/issues/1).

**Comment by foodelevator** [comment]
Vad synsk du är som föreslår båda de två lösningar som senare implementerades. Eller "inspirerades" jag av det här? Ingen vet.

Det som är kvar här är i alla fall att markera rätt saker som känsliga eftersom stöd för detta nu är implementerat i taitan.

**Comment by Herkarl** [comment]
Föreslår att vi stänger det här issue:t och har kvar [styrdokument#219](https://github.com/datasektionen/styrdokument/issues/219) för att markera mörkläggningssaker
